# Generated by Django 5.0.3 on 2024-04-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('semester_number', models.IntegerField()),
                ('is_current', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_number',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II')], null=True),
        ),
        migrations.CreateModel(
            name='ResultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_published', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework_marks', models.IntegerField(default=None, null=True)),
                ('exam_marks', models.IntegerField(default=None, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('result_permission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resultpermission')),
                ('semester', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.semester')),
            ],
        ),
    ]
