# Generated by Django 5.0.3 on 2024-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II')], null=True),
        ),
    ]
