# Generated by Django 5.0.3 on 2024-04-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_course_enrollment_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='coursework_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resultpermission',
            name='course_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
